operating-mode: normal
server:
     error:
          include-message: always
          include-binding-errors: always
spring:
     datasource:
          password: password
          url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
          username: sa
          driver-class-name: org.h2.Driver
     jpa:
          hibernate:
               ddl-auto: update
          properties:
               hibernate:
                    dialect: org.hibernate.dialect.H2Dialect
                    format_sql: true
          show-sql: true
     sql:
          init:
               mode: never
     mail:
          host: smtp.gmail.com
          port: 587
          username: crmpap111@gmail.com
          password: sfmfidcscqondtjt
          properties:
               mail:
                    smtp:
                         ssl:
                              trust: '*'
                         auth: true
                         starttls:
                              enable: true
                         connectiontimeout: 5000
                         timeout: 3000
                         writetimeout: 5000
